"""Slice-wise G-code generation from a G-plan map (paper, Sec. 3.4).

Each slice of the (infilled) G-plan map is turned into ordered toolpaths on the
printer XY plane:

  * perimeters follow the contours of the occupancy map ``M``, one pass per wall,
    the mask being eroded by one line width between passes;
  * the interior is filled with serpentine rows whose pitch follows the requested
    infill density, alternating direction every slice;
  * the extrusion of a segment is its deposited volume divided by the filament
    cross-section, ``dE = line_width * layer_height * length / A_filament``,
    modulated by the flow map ``Q`` sampled at the middle of the segment. ``Q`` is
    expected in [0, 1], the range GPNet predicts; a raw flow map straight out of
    :func:`~printanything.gplan.gcode_to_gplan.gcode_to_gplan` holds physical
    volume rates instead, so compile those with ``use_flow=False``.

The physical coordinate of a pixel ``u = (ux, uy)`` is its centre, Eq. (4)::

    x = (ux + 0.5) * px_mm + x0
    y = (uy + 0.5) * px_mm + y0

where ``(x0, y0)`` is the raster origin in millimetres. Pass ``bed_center_xy_mm``
to recentre the object on the print bed, which is what the physical prints of
Sec. 5.8 use.
"""

import json
import math
import os
from dataclasses import dataclass
from typing import List, Optional, TextIO, Tuple

import numpy as np
from skimage import measure
from skimage.morphology import binary_erosion, disk
from tqdm import tqdm

from .io import find_manifest

__all__ = ["GCodeConfig", "gplan_to_gcode"]


@dataclass
class GCodeConfig:
    """Printing parameters of the compiler.

    ``line_width`` and ``infill_density`` default to the values recorded in the
    manifest (nozzle diameter and the density of the reference slicing).
    """

    perimeter_speed: float = 40.0  # mm/s
    infill_speed: float = 60.0  # mm/s
    travel_speed: float = 150.0  # mm/s
    line_width: Optional[float] = None  # mm, None -> nozzle diameter
    walls: int = 3
    infill_density: Optional[float] = None  # 0..1, None -> manifest value
    infill_overlap: float = 0.12  # wall/infill overlap fraction
    perimeter_eps_px: float = 0.5  # contour simplification tolerance, px
    max_volumetric_flow: Optional[float] = None  # mm^3/s, clamps the feedrate
    use_flow: bool = True  # modulate extrusion with Q
    flow_scale: float = 1.0
    bed_center_xy_mm: Optional[Tuple[float, float]] = None


def filament_area(diameter_mm: float) -> float:
    return math.pi * (diameter_mm * 0.5) ** 2


def find_all_contours(occ: np.ndarray) -> List[np.ndarray]:
    return measure.find_contours(occ.astype(np.uint8), level=0.5)


def simplify_contour(contour: np.ndarray, eps_px: float) -> np.ndarray:
    if eps_px is None or eps_px <= 0.0:
        return contour
    simplified = measure.approximate_polygon(contour, tolerance=eps_px)
    return contour if simplified.shape[0] < 3 else simplified


def sample_flow(
    Q: np.ndarray, x_mm: float, y_mm: float, origin: Tuple[float, float], px_mm: float
) -> float:
    """Bilinearly sample the flow map at a physical position (clamped, >= 0)."""
    H, W = Q.shape
    x_px = min(max((x_mm - origin[0]) / px_mm, 0.0), W - 1)
    y_px = min(max((y_mm - origin[1]) / px_mm, 0.0), H - 1)

    x0, y0 = int(math.floor(x_px)), int(math.floor(y_px))
    x1, y1 = min(W - 1, x0 + 1), min(H - 1, y0 + 1)
    fx, fy = x_px - x0, y_px - y0

    q = (
        float(Q[y0, x0]) * (1 - fx) * (1 - fy)
        + float(Q[y0, x1]) * fx * (1 - fy)
        + float(Q[y1, x0]) * (1 - fx) * fy
        + float(Q[y1, x1]) * fx * fy
    )
    return max(0.0, q)


def emit_header(f: TextIO, material: dict) -> None:
    nozzle = material.get("nozzle_temp_c")
    bed = material.get("bed_temp_c")
    f.write("; Generated by PrintAnything (printanything.gplan.gplan_to_gcode)\n")
    if bed is not None:
        f.write(f"M140 S{int(round(bed))}\n")
    if nozzle is not None:
        f.write(f"M104 S{int(round(nozzle))}\n")
    if bed is not None:
        f.write(f"M190 S{int(round(bed))}\n")
    if nozzle is not None:
        f.write(f"M109 S{int(round(nozzle))}\n")
    f.write("G21\nG90\nM83\nG28\nG92 E0\n")


def emit_footer(f: TextIO) -> None:
    f.write("\n; end\nM104 S0\nM140 S0\nG91\nG1 E-2 F1800\nG1 Z10 F600\nG90\nM84\n")


class _SliceWriter:
    """Emits the moves of one slice and accumulates the extruded filament."""

    def __init__(
        self,
        f: TextIO,
        cfg: GCodeConfig,
        *,
        origin: Tuple[float, float],
        px_mm: float,
        layer_height: float,
        line_width: float,
        filament_area_mm2: float,
        Q: Optional[np.ndarray],
    ):
        self.f = f
        self.cfg = cfg
        self.origin = origin
        self.px_mm = px_mm
        self.layer_height = layer_height
        self.line_width = line_width
        self.Af = filament_area_mm2
        self.Q = Q
        self.total_E = 0.0

    def to_mm(self, ux: float, uy: float) -> Tuple[float, float]:
        """Pixel indices -> physical coordinates of the pixel centre, Eq. (4)."""
        return (
            self.origin[0] + (ux + 0.5) * self.px_mm,
            self.origin[1] + (uy + 0.5) * self.px_mm,
        )

    def _feedrate(self, speed_mm_s: float) -> float:
        f_mm_min = speed_mm_s * 60.0
        if self.cfg.max_volumetric_flow:
            limit = (self.cfg.max_volumetric_flow * 60.0) / (self.line_width * self.layer_height)
            f_mm_min = min(f_mm_min, limit)
        return f_mm_min

    def travel(self, x_mm: float, y_mm: float, z_mm: Optional[float] = None) -> None:
        z = f" Z{z_mm:.3f}" if z_mm is not None else ""
        self.f.write(f"G0 X{x_mm:.3f} Y{y_mm:.3f}{z} F{self.cfg.travel_speed * 60.0:.0f}\n")

    def extrude_to(
        self, x_mm: float, y_mm: float, from_xy: Tuple[float, float], speed_mm_s: float
    ) -> None:
        length = math.hypot(x_mm - from_xy[0], y_mm - from_xy[1])
        dE = (self.line_width * self.layer_height * length) / self.Af
        if self.Q is not None:
            mid = (0.5 * (x_mm + from_xy[0]), 0.5 * (y_mm + from_xy[1]))
            dE *= sample_flow(self.Q, mid[0], mid[1], self.origin, self.px_mm) * self.cfg.flow_scale
        self.total_E += dE
        self.f.write(
            f"G1 X{x_mm:.3f} Y{y_mm:.3f} F{self._feedrate(speed_mm_s):.0f} E{dE:.5f}\n"
        )


def _emit_perimeters(w: _SliceWriter, occ: np.ndarray) -> None:
    """One contour pass per wall, eroding the mask by a line width in between."""
    cfg = w.cfg
    work = occ.astype(bool)
    footprint = disk(max(1, int(round((w.line_width / w.px_mm) / 2.0))))

    for wall in range(max(1, cfg.walls)):
        contours = find_all_contours(work.astype(np.uint8))
        if not contours:
            break
        for island, contour in enumerate(contours):
            contour = simplify_contour(contour, cfg.perimeter_eps_px)
            if contour.shape[0] < 3:
                continue
            loop = [w.to_mm(x, y) for (y, x) in contour]  # contours are (row, col)
            w.travel(loop[0][0], loop[0][1])
            w.f.write(f";TYPE:PERIMETER ;WALL:{wall + 1}/{cfg.walls} ;ISLAND:{island}\n")
            last = loop[0]
            for point in loop[1:] + loop[:1]:  # close the loop
                w.extrude_to(point[0], point[1], last, cfg.perimeter_speed)
                last = point

        work = binary_erosion(work, footprint=footprint)
        if not work.any():
            break


def _row_spans(row: np.ndarray) -> List[Tuple[int, int]]:
    """Maximal runs of occupied pixels in one raster row, as (start, end) pairs."""
    occupied = np.flatnonzero(row > 0)
    if occupied.size == 0:
        return []
    breaks = np.flatnonzero(np.diff(occupied) > 1)
    starts = np.concatenate(([occupied[0]], occupied[breaks + 1]))
    ends = np.concatenate((occupied[breaks], [occupied[-1]]))
    return list(zip(starts.tolist(), ends.tolist()))


def _emit_infill(w: _SliceWriter, occ: np.ndarray, density: float, flip: bool) -> None:
    """Serpentine rows over the occupancy mask, alternating direction per slice."""
    cfg = w.cfg
    H, W = occ.shape
    pitch = max(0.2 * w.line_width, (w.line_width / max(density, 1e-3)) * (1.0 - cfg.infill_overlap))
    step = max(1, int(round(pitch / w.px_mm)))

    w.f.write(f";TYPE:INFILL ;PITCH:{pitch:.3f}\n")
    for yi in range(0, H, step):
        for x0, x1 in _row_spans(occ[yi]):
            if flip:
                x0, x1 = x1, x0
            start = w.to_mm(x0, yi)
            end = w.to_mm(x1, yi)
            w.travel(start[0], start[1])
            w.extrude_to(end[0], end[1], start, cfg.infill_speed)


def gplan_to_gcode(gplan_path, out_path, cfg: Optional[GCodeConfig] = None, progress: bool = True) -> str:
    """Compile a G-plan map into a printable G-code file.

    Args:
        gplan_path: manifest file, or the folder that contains it.
        out_path: destination ``.gcode`` file.
        cfg: printing parameters; defaults to :class:`GCodeConfig`.

    Returns:
        ``out_path``.
    """
    cfg = cfg or GCodeConfig()

    gplan_path = str(gplan_path)
    if os.path.isdir(gplan_path):
        found = find_manifest(gplan_path)
        if found is None:
            raise FileNotFoundError(f"No G-plan manifest under {gplan_path}")
        gplan_path = found

    with open(gplan_path, "r") as fh:
        manifest = json.load(fh)
    root = os.path.dirname(gplan_path)

    layers = manifest["layers"]
    base_lh = manifest.get("global", {}).get("base_layer_height_mm") or 0.2
    printer = manifest.get("printer_profile", {})
    nozzle = float(printer.get("nozzle_diameter", 0.4))
    Af = filament_area(float(printer.get("filament_diameter", 1.75)))

    line_width = float(cfg.line_width if cfg.line_width is not None else nozzle)
    density = float(
        cfg.infill_density
        if cfg.infill_density is not None
        else (manifest.get("global", {}).get("infill_density") or 0.2)
    )

    os.makedirs(os.path.dirname(os.path.abspath(out_path)) or ".", exist_ok=True)
    total_E = 0.0

    with open(out_path, "w") as g:
        emit_header(g, manifest.get("material_profile", {}))

        iterator = enumerate(layers)
        for li, layer in tqdm(list(iterator), desc="slices", disable=not progress):
            raster = layer["raster"]
            H, W, px_mm = int(raster["H"]), int(raster["W"]), float(raster["px_mm"])
            origin = tuple(raster.get("origin_xy_mm", [0.0, 0.0]))
            if cfg.bed_center_xy_mm is not None:
                # Place the centre of the raster at the centre of the bed.
                origin = (
                    cfg.bed_center_xy_mm[0] - 0.5 * W * px_mm,
                    cfg.bed_center_xy_mm[1] - 0.5 * H * px_mm,
                )

            z_mm = float(layer.get("z_mm", (li + 1) * base_lh))
            layer_h = float(layer.get("layer_height_mm", base_lh))
            occ = np.load(os.path.join(root, raster["occupancy_uri"]))

            Q = None
            if cfg.use_flow and raster.get("flow_uri"):
                q_path = os.path.join(root, raster["flow_uri"])
                if os.path.exists(q_path):
                    candidate = np.load(q_path).astype(np.float32)
                    if candidate.shape == (H, W):
                        Q = candidate
                    else:
                        print(f"[gplan_to_gcode] slice {li}: flow map {candidate.shape} "
                              f"does not match raster {(H, W)}; ignoring it.")

            g.write(f"\n;LAYER:{li}\n")
            # The slice height is emitted unconditionally: a slice whose occupancy
            # touches the raster border yields no contour, and a Z that only rode
            # along with a perimeter would then be missing entirely.
            g.write(f"G0 Z{z_mm:.3f} F{cfg.travel_speed * 60.0:.0f}\n")
            writer = _SliceWriter(
                g, cfg,
                origin=origin, px_mm=px_mm, layer_height=layer_h,
                line_width=line_width, filament_area_mm2=Af, Q=Q,
            )
            _emit_perimeters(writer, occ)
            _emit_infill(writer, occ, density, flip=(li % 2 == 1))
            total_E += writer.total_E

        g.write(f"\n; STATS: total filament (mm) ~ {total_E:.2f}\n")
        emit_footer(g)

    return str(out_path)
